---
title: "Yearly AIRSIS Data"
author: "Mazama Science"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=5)
```

# Setup

Start by loading the PWFSLSmoke package and loading the data. 

```{r Setup, message=FALSE}
suppressPackageStartupMessages({
  library(PWFSLSmoke)
  library(ggplot2)
  library(gridExtra)
}
  )
logger.setLevel(ERROR)
load("~/Data/airsis/airsis_2015.RData")
load("~/Data/airsis/airsis_2016.Rdata")
```

# Orientation

```{r mapping}
monitorLeaflet(airsis_2015)
monitorLeaflet(airsis_2016)
```

```{r}
days2015 <- sum(!is.na(airsis_2015$data[-1]))/24
days2016 <- sum(!is.na(airsis_2016$data[-1]))/24
deployments2015 <- ncol(airsis_2015$data) - 1
deployments2016 <- ncol(airsis_2016$data) - 1
```

Let's see how they were distributed through time:

```{r}
counts2015 <-  data.frame(time = airsis_2015$data$datetime, count = apply(airsis_2015$data[-1], 1, function(x) sum(!is.na(x))))
counts2016 <-  data.frame(time = airsis_2016$data$datetime, count = apply(airsis_2016$data[-1], 1, function(x) sum(!is.na(x))))
plot1 <- ggplot(counts2015, aes(time, count))+
  geom_bar(stat="identity")+
  labs(title='2015', subtitle='number of deployments each hour')
plot2 <- ggplot(counts2016, aes(time, count))+
  geom_bar(stat="identity")+
  labs(title='2016', subtitle='number of deployments each hour')
grid.arrange(plot1, plot2, nrow = 2)
```

```{r monthly_maps}
basemap <- esriMap_getMap(bboxString = '-168.9,20.18,-58.68,70.51')
layout(matrix(c(3,3,1,2), 2, 2, byrow = TRUE), widths=c(1,1), heights=c(1,3)) 
for ( month in 1:12) {
  # First 2015
  tlim2015 <- if (month < 12) {
    paste0('2015', stringr::str_pad(as.character(c(month, month+1)), 2, side = 'left', "0"), '01')
  } else {
    c('20151201', '20160101')
  }
  ws_monitor2015 <- monitor_subset(airsis_2015, tlim = tlim2015)
  month_str <- strftime(ws_monitor2015$data$datetime[30], format = "%B")
  tlim2016 <- if (month < 12) {
    paste0('2016', stringr::str_pad(as.character(c(month, month+1)), 2, side = 'left', "0"), '01')
  } else {
    c('20161201', '20170101')
  }
  ws_monitor2016 <- monitor_subset(airsis_2016, tlim = tlim2016)
  monitorEsriMap(ws_monitor2015, mapRaster = basemap, main = '2015')
  monitorEsriMap(ws_monitor2016, mapRaster = basemap, main = '2016')
  plot(0,0,axes = F, col = 'transparent')
  text(0,0,month_str, cex = 3)
  }
```


