---
title: "Introduction to dplyr"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to dplyr}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4L, tibble.print_max = 4L)
library(dplyr)
library(ggplot2)
```

When working with data you must:

* Figure out what you want to do.

* Describe those tasks in the form of a computer program.

* Execute the program.

The dplyr package makes these steps fast and easy:

* By constraining your options, it simplifies how you can think about common data manipulation tasks.

* It provides simple "verbs", functions that correspond to the most common data manipulation tasks, to help you translate those thoughts into code.

* It uses efficient data storage backends, so you spend less time waiting for the computer.

This document introduces you to dplyr's basic set of tools, and shows you how to apply them to data frames. Other vignettes provide more details on specific topics:

* databases: Besides in-memory data frames, dplyr also connects to out-of-memory, remote databases. And by translating your R code into the appropriate SQL, it allows you to work with both types of data using the same set of tools.

* benchmark-baseball: see how dplyr compares to other tools for data
  manipulation on a realistic use case.

* window-functions: a window function is a variation on an aggregation
  function. Where an aggregate function uses `n` inputs to produce 1 
  output, a window function uses `n` inputs to produce `n` outputs.
