################################################################################
# Makefile for building and running docker containers


# PRODUCTION version -----------------------------------------------------------
production_build:
	docker build --no-cache -t mazamascience/pwfslsmoke:1.1.28 -t mazamascience/pwfslsmoke:latest .

