#' @keywords WRCC
#' @export
#' @title Create WRCC Site Location Metadata Tibble
#' @param tbl single site WRCC tibble after metadata enhancement
#' @param unitID character or numeric WRCC unit identifier
#' @param pwfslDataIngestSource identifier for the source of monitoring data, e.g. \code{'WRCC', 'WRCC_DUMPFILE', ...}
#' @param existingMeta existing 'meta' dataframe from which to obtain metadata for known monitor deployments
#' @return A \code{meta} dataframe for use in a \emph{ws_monitor} object.
#' @description After a WRCC tibble has been enhanced with 
#' additional columns generated by \code{addClustering} we are ready to 
#' pull out site information associated with unique deployments.
#' 
#' These will be rearranged into a dataframe organized as deployment-by-property
#' with one row for each monitor deployment.
#'
#' This site information found in \code{tbl} is augmented so that we end up with a uniform
#' set of properties associated with each monitor deployment. The list of
#' columns in the returned \code{meta} dataframe is:
#' 
#' \preformatted{
#' > names(p$meta)
#'  [1] "monitorID"             "longitude"             "latitude"             
#'  [4] "elevation"             "timezone"              "countryCode"          
#'  [7] "stateCode"             "siteName"              "agencyName"           
#' [10] "countyName"            "msaName"               "monitorType"          
#' [13] "monitorInstrument"     "aqsID"                 "pwfslID"              
#' [16] "pwfslDataIngestSource" "telemetryAggregator"   "telemetryUnitID"      
#' }
#' 
#' @seealso \code{\link{addGoogleMetadata}}
#' @seealso \code{\link{addMazamaMetadata}}


wrcc_createMetaDataframe <- function(tbl,
                                     unitID=as.character(NA),
                                     pwfslDataIngestSource='WRCC',
                                     existingMeta=NULL) {
  
  logger.info(" ----- wrcc_createMetaDataframe() ----- ")
  
  # Sanity check -- tbl must have a monitorType
  if ( !'monitorType' %in% names(tbl) ) {
    logger.error("No 'monitorType' column found in 'tbl' tibble with columns: %s", paste0(names(tbl), collapse=", "))
    stop(paste0("No 'monitorType' column found in 'tbl' tibble."))
  }
  
  monitorType <- unique(tbl$monitorType)
  
  # Sanity check -- tbl must have only one monitorType
  if ( length(monitorType) > 1 ) {
    logger.error("Multilpe monitor types found in 'tbl' tibble: %s", paste0(monitorType, collapse=", "))
    stop(paste0("Multiple monitor types found in 'tbl' tibble."))
  }
  
  monitorType <- monitorType[1]
  
  # Sanity check -- tbl must have deploymentID
  if ( !'deploymentID' %in% names(tbl) ) {
    logger.error("No 'deploymentID' column found in 'tbl' tibble with columns: %s", paste0(names(tbl), collapse=", "))
    stop(paste0("No 'deploymentID' column found in 'tbl' tibble.  Have you run addClustering()?"))
  }
  
  # Pull out unique deployments
  tbl <- tbl[!duplicated(tbl$deploymentID),]
  
  logger.debug("Tibble contains %d unique deployment(s)", nrow(tbl))
  
  # Our tibble now contains the following columns:
  #
  # > names(tbl)
  #  [1] "DateTime"       "GPSLat"         "GPSLon"         "Type"           "SerialNumber"  
  #  [6] "ConcRT"         "Misc1"          "AvAirFlw"       "AvAirTemp"      "RelHumidity"   
  # [11] "Misc2"          "SensorIntAT"    "SensorIntRH"    "WindSpeed"      "WindDir"       
  # [16] "BatteryVoltage" "Alarm"          "monitorName"    "monitorType"    "datetime"      
  # [21] "deploymentID"   "medoidLon"      "medoidLat"     
  #
  # The PWFSLSmoke v1.0 data model contains the following parameters
  # 
  #  [1] "monitorID"             "longitude"             "latitude"             
  #  [4] "elevation"             "timezone"              "countryCode"          
  #  [7] "stateCode"             "siteName"              "agencyName"           
  # [10] "countyName"            "msaName"               "monitorType"          
  # [13] "monitorInstrument"     "aqsID"                 "pwfslID"              
  # [16] "pwfslDataIngestSource" "telemetryAggregator"   "telemetryUnitID"      
  
  # NOTE:  'meta' must be a dataframe because it has rownames which are deprecated in tibbles
  # Create empty dataframe
  meta <- as.data.frame(matrix(nrow=nrow(tbl),ncol=18))
  
  colNames <- c("monitorID", "longitude", "latitude",
                "elevation", "timezone", "countryCode",
                "stateCode", "siteName", "agencyName",
                "countyName", "msaName", "monitorType",
                "monitorInstrument", "aqsID", "pwfslID",
                "pwfslDataIngestSource", "telemetryAggregator", "telemetryUnitID")
  
  names(meta) <- colNames
  
  # Assign data where we have it
  # NOTE:  We use monitorID as a unique identifier instead of AQSID so that we can be
  # NOTE:  consistent when working with non-AirNow datasets.
  meta$longitude <- tbl$medoidLon
  meta$latitude <- tbl$medoidLat
  meta$pwfslID <- paste0( make.names(tbl$monitorName), '__', tbl$deploymentID )
  meta$monitorID <- meta$pwfslID
  meta$monitorType <- tbl$monitorType
  meta$pwfslDataIngestSource <- pwfslDataIngestSource
  meta$telemetryAggregator <- 'wrcc'
  meta$telemetryUnitID <- unitID
  
  # Assign rownames
  rownames(meta) <- meta$monitorID
  
  # Add timezones, state and country codes
  meta <- addMazamaMetadata(meta, existingMeta=existingMeta)
  
  # TODO:  Could assign other spatial identifiers like EPARegion, etc.
  
  # agencyName
  # TODO:  Can agencyName be inferred from monitorName?
  #   NPSMask <- stringr::str_detect(meta$monitorID,'\\.NPS\\.')
  #   USFSMask <- stringr::str_detect(meta$monitorID,'\\.USFS\\.')
  #   meta$agencyName[NPSMask] <- 'National Park Servsice'
  #   meta$agencyName[USFSMask] <- 'United States Forest Service'
  
  # Add elevation, siteName and countyName
  meta <- addGoogleMetadata(meta, existingMeta=existingMeta)
  
  # Convert some columns to character even if they have all NA
  characterColumns <- c('siteName','agencyName','countyName','msaName','monitorType',
                        'monitorInstrument','aqsID')
  for (colName in characterColumns) {
    meta[[colName]] <- as.character(meta[[colName]])
  }
  
  logger.info("Created 'meta' dataframe with %d rows and %d columns", nrow(meta), ncol(meta))
  
  return(meta)
  
}
