---
title: "Loading Data"
author: "Mazama Science"
date: "2021-02-17"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
knitr::opts_chunk$set(fig.width = 7, fig.height = 5)
```

## Welcome to the data archive

* WIP: temporary monitors (WRCC, AIRSIS) vs. permanent monitors (AirNow)

The [data archive](https://haze.airfire.org/monitoring/) hosts PM2.5 data generated by temporary and permanent monitors. The agencies providing this data are: [AIRSIS](https://app.airsis.com/USFS) and [WRCC](http://www.wrcc.dri.edu)(Western Regional Climate Cente), with temporary monitors; [AirNow](https://www.airnow.gov)) with permanet monitors. 

* WIP: three types of archive files — hourly, daily, monthly, 

Each agency provides hourly, daily, and annual data. Additionally, Airnow provides montly data. Following, an explanation of the methods used to update the different files:
* the hourly files are updated multiple times an hour (every two minutes) and contain data for the previous 10 days. 
* the daily files are updated once a day, shortly after midnight and contain data for the previous 45 days.
* the monthly files are updated on the 15'th of the following month. For instance, July is updated on the 15th of August. **Jon, do I remeber right?**
* the annual files are updated on the 15'th of each month and cover the period from the beginning of the year to the end of the last month. 
Latest data from all agencies are available in [latest/RData](https://haze.airfire.org/monitoring/latest/RData/) subdirectory. 

* WIP: structure of the archive
The data archive si structured as follow:
* at the first level, each agency has its own folder (i.e [AIRSIS](https://haze.airfire.org/monitoring/AIRSIS/), [AirNow](https://haze.airfire.org/monitoring/AirNow/), [WRCC](https://haze.airfire.org/monitoring/WRCC/)).
* at the second level, each agency has the `RData/` folder.
* at the third level, each agency has yearly folders (e.g. `2010/`) and the `latest/` folder. The latter contains hourly (e.g. `agencyName_PM2.5_latest10.RData`) and daily (e.g. `agencyName_PM2.5_latest45.RData`) data. 
* at the fourth level, each agency has annual data (e.g. `agencyName_PM2.5_2019.RData`). Additionally, AirNow has monthly folders (e.g. `01/`), and therefore a fith level containing monthly data (e.g. AirNow_PM2.5_2018_06.RData).


## loading files directly from the archive with get(load(url(…)))
* TO DO: loading functions. left here 
* TO DO: ~loadLatest, ~loadDaily, ~loadAnnual
* TO DO: monitor_load() — the preferred function for general data loading
* TO DO: note — no ability to cross year boundaries (OK because there are few wildfires on New Year’s Eve)


## examples
* TO DO: most current example -- load and create plot the using Latest data for Washington
* TO DO: archival example — load and create plot using data from OR-ID-WA during 2015 (this is the package dataset Northwest Megafires but obtain the data from the archive)
