---
title: "PWFSLSmoke Tutorial"
author: "Mazama Science"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PWFSLSmoke R Package

```
Utilities for working with PM2.5 monitoring data available
from the AirNow, AIRSIS, WRCC and others.
```

## Background

The USFS Pacific Wildland Fire Sciences Lab [AirFire](http://www.airfire.org) team works
to model wildland fire emissions and has created the BlueSky Modeling Framework. This
system  integrates a wide collection of models along a smoke modeling pipeline (fire 
information, fuel loadings, consumption modeling, emissions modeling, time rate of 
emissions modeling, plume height estimations, and smoke trajectory and dispersion 
modeling). The resulting model output has been integrated into many different smoke 
prediction systems and scientific modeling efforts.

The **PWFSLSmoke** R package is being developed for PWFSL to help modelers and scientists
more easily work with PM2.5 data from monitoring locations across North America.

The package includes functionality to make it easier to:

 * download and work with monitoring data
 * create maps and timeseries plots of monitoring data
 * convert between local and GMT times

## Installation

This package is designed to be used with [R](https://cran.r-project.org) (>= 3.1.0) and
[RStudio](http://rstudio.com) so make sure you have those installed first.

Users will want to install the **devtools** package to have access to latest versions
of some packages that are not yet available on CRAN.

The following packages should be installed with devtools by typing the following at the RStudio console:

```
devtools::install_github('rstudio/dygraphs')
devtools::install_github('rstudio/leaflet')
devtools::install_github('mazamascience/MazamaSpatialUtils', build_vignettes=TRUE)
devtools::install_github('mazamascience/PWFSLSmoke', build_vignettes=TRUE)
```

Any work with spatial data, *e.g.* assigning counties or watersheds, will require installation of required
spatial datasets. To get these datasets you should execute the following commands from a shell terminal:

```
mkdir ~/Data
cd ~/Data
curl -O http://smoke.airfire.org/RData/Spatial.tar.gz
tar -xzf Spatial.tar.gz
```

## Table of Contents

* 1: Crash course in R
* 2: PWFSLSmoke's Data Model
* 3: Obtaining Data
* 4: Manipulating Data
* 5: Visualizing Data
